version: "3.6"

networks:
  grafana:
    external:
      name: ritta-grafana

volumes:
  grafana-data:

services:
  grafana:
    # https://hub.docker.com/r/grafana/grafana/tags
    image: grafana/grafana:8.0.6
    ports:
      - "3001:3000"
    networks:
      - "grafana"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./dashboards:/dashboards
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel"
  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - ../../logs/:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana