version: '3'
services:
  gateway:
    build: ./apps/gateway
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
    ports:
      - '3001:3001'
    networks:
      - ritta

  users:
    build: ./apps/users
    environment:
      - NODE_ENV=production
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
    ports:
      - '3002:3002'
    networks:
      - ritta

  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-vols/ritta/rabbitmq/data:/var/lib/rabbitmq/
      - ~/.docker-vols/ritta/rabbitmq/log:/var/log/rabbitmq
    networks:
      - ritta

networks:
  ritta:
    driver: bridge
