version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ritta
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 12

  gateway:
    image: ghcr.io/rittaschool/ritta:master-gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - REDIS_URI=redis://gateway-db:6379
      - JWT_SIGNING_SECRET=RITTATESTSIGNINGKEY
      - FRONTEND_PUBLIC_URL=http://localhost:3002
    ports:
      - '3000:3000'
    networks:
      - ritta
  auth:
    image: ghcr.io/rittaschool/ritta:master-auth
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - SIGNING_KEY=RITTATESTSIGNINGKEY
    networks:
      - ritta

  users:
    image: ghcr.io/rittaschool/ritta:master-users
    depends_on:
      rabbitmq:
        condition: service_healthy
      users_db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - MONGO_URI=mongodb://ritta:password@users_db:27017/ritta?authSource=admin
    networks:
      - ritta

  messages:
    image: ghcr.io/rittaschool/ritta:master-messages
    depends_on:
      rabbitmq:
        condition: service_healthy
      messages_db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - MONGO_URI=mongodb://ritta:password@messages_db:27019/ritta?authSource=admin
    networks:
      - ritta

  users_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ritta
      - MONGO_INITDB_ROOT_USERNAME=ritta
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - ritta
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 10s
      retries: 12

  messages_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ritta
      - MONGO_INITDB_ROOT_USERNAME=ritta
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - ritta
    ports:
      - "127.0.0.1:27019:27017"
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 10s
      retries: 12
      
  gateway-db:
    image: redislabs/rejson:latest
    networks:
      - databases
    ports:
      - "6380:6379"

  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - loki

networks:
  ritta:
    driver: bridge
  loki:
