version: '3'
services:
  gateway:
    build: ./apps/gateway
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - '3001:3001'

  rabbitmq:
    image: rabbitmq:3.9.7
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-vols/rabbitmq/data:/var/lib/rabbitmq/
      - ~/.docker-vols/rabbitmq/log:/var/log/rabbitmq
    networks:
      - ritta

networks:
  ritta:
    driver: bridge
