version: "3.6"

networks:
  databases:
    external:
      name: ritta-databases

volumes:
  users-db: null
  messages-db: null
  core-db: null

services:
  users_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ritta
      - MONGO_INITDB_ROOT_USERNAME=ritta
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - users-db:/data/usr-db
    ports:
      - "27018:27017"
    networks:
      - databases
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 10s
      retries: 12

  messages_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ritta
      - MONGO_INITDB_ROOT_USERNAME=ritta
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - messages-db:/data/msg-db
    ports:
      - "27019:27017"
    networks:
      - databases
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 10s
      retries: 12

  core_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=ritta
      - MONGO_INITDB_ROOT_USERNAME=ritta
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - core-db:/data/core-db
    ports:
      - "27020:27017"
    networks:
      - databases
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 10s
      retries: 12
  
  gateway-db:
    image: redislabs/rejson:latest
    networks: 
      - databases
    ports:
      - "6380:6379"
