version: "3.6"

networks:
  rabbitmq:
    external:
      name: ritta-rmq
  databases:
    external:
      name: ritta-databases
  services: null

services:
  gateway:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=gateway
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - REDIS_URI=redis://gateway-db:6379
      - JWT_SIGNING_SECRET=RITTATESTSIGNINGKEY
      - FRONTEND_PUBLIC_URL=https://code.midka.dev
    ports:
      - '3000:3000'
    networks:
      - rabbitmq
      - services
      - databases
    volumes:
      - ../../logs/gateway.log:/home/app/logs/all.log
      - ../../apps/gateway:/home/app
      - ../../apps/gateway/dist:/home/app/dist
      - ../../apps/gateway/node_modules:/home/app/node_modules

  core:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=core
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - SIGNING_KEY=RITTATESTSIGNINGKEY
      - INSTANCE_NAME=Ritta Testing
    networks:
      - rabbitmq
      - services
    volumes:
      - ../../apps/core:/home/app
      - ../../apps/core/dist:/home/app/dist
      - ../../apps/core/node_modules:/home/app/node_modules

  auth:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=auth
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - SIGNING_KEY=RITTATESTSIGNINGKEY
    networks:
      - rabbitmq
      - services
    volumes:
      - ../../logs/auth.log:/home/app/logs/all.log
      - ../../apps/auth:/home/app
      - ../../apps/auth/dist:/home/app/dist
      - ../../apps/auth/node_modules:/home/app/node_modules

  users:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=users
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - MONGO_URI=mongodb://ritta:password@users_db:27017/ritta?authSource=admin
    networks:
      - rabbitmq
      - services
      - databases
    volumes:
      - ../../logs/users.log:/home/app/logs/all.log
      - ../../apps/users:/home/app
      - ../../apps/users/dist:/home/app/dist
      - ../../apps/users/node_modules:/home/app/node_modules
  messages:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=messages
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - MONGO_URI=mongodb://ritta:password@messages_db:27017/ritta?authSource=admin
    networks:
      - rabbitmq
      - services
      - databases
    volumes:
      - ../../logs/messages.log:/home/app/logs/all.log
      - ../../apps/messages:/home/app
      - ../../apps/messages/dist:/home/app/dist
      - ../../apps/messages/node_modules:/home/app/node_modules