version: '3.6'

networks:
  rabbitmq:
    external:
      name: ritta-rmq
  databases:
    external:
      name: ritta-databases
  services: null

services:
  gateway:
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - SCOPE=gateway
        - USER_ID=${USER_ID:-0}
        - GROUP_ID=${GROUP_ID:-0}
    command: /app/node_modules/.bin/nest start --watch
    environment:
      - NODE_ENV=development
      - PORT=3000
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - REDIS_URI=redis://gateway-db:6379
      - JWT_SIGNING_SECRET=RITTATESTSIGNINGKEY
      - FRONTEND_PUBLIC_URL=https://code.midka.dev
    ports:
      - '3000:3000'
    networks:
      - rabbitmq
      - services
      - databases
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - ../../logs/gateway.log:/app/apps/gateway/logs/all.log
      - ../../apps/gateway:/apps/gateway/app
      - ../../apps/gateway/dist:/app/apps/gateway/dist
      - ../../apps/gateway/node_modules:/app/apps/gateway/node_modules

  core:
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - SCOPE=core
        - USER_ID=${USER_ID:-0}
        - GROUP_ID=${GROUP_ID:-0}
    command: /app/node_modules/.bin/nest start --watch
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - SIGNING_KEY=RITTATESTSIGNINGKEY
      - INSTANCE_NAME=Ritta Testing
      - MONGO_URI=mongodb://ritta:password@core_db:27017/ritta?authSource=admin
    networks:
      - rabbitmq
      - services
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - ../../apps/core:/app/apps/core
      - ../../apps/core/dist:/app/apps/core/dist
      - ../../apps/core/node_modules:/app/apps/core/node_modules

  auth:
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - SCOPE=auth
        - USER_ID=${USER_ID:-0}
        - GROUP_ID=${GROUP_ID:-0}
    command: /app/node_modules/.bin/nest start --watch
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - SIGNING_KEY=RITTATESTSIGNINGKEY
    networks:
      - rabbitmq
      - services
    volumes:
      - ../../:/app
      - /app/node_modules/argon2
      - ../../node_modules:/app/node_modules
      - ../../logs/auth.log:/app/apps/auth/logs/all.log
      - ../../apps/auth:/apps/auth/app
      - ../../apps/auth/dist:/app/apps/auth/dist
      - ../../apps/auth/node_modules:/app/apps/auth/node_modules

  users:
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - SCOPE=users
        - USER_ID=${USER_ID:-0}
        - GROUP_ID=${GROUP_ID:-0}
    command: /app/node_modules/.bin/nest start --watch
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - MONGO_URI=mongodb://ritta:password@users_db:27017/ritta?authSource=admin
    networks:
      - rabbitmq
      - services
      - databases
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - /app/node_modules/argon2
      - ../../logs/users.log:/app/apps/users/logs/all.log
      - ../../apps/users:/app/apps/users
      - ../../apps/users/dist:/app/apps/users/dist
      - ../../apps/users/node_modules:/app/apps/users/node_modules
  messages:
    build:
      context: ../../
      dockerfile: Dockerfile.dev
      args:
        - SCOPE=messages
        - USER_ID=${USER_ID:-0}
        - GROUP_ID=${GROUP_ID:-0}
    command: /app/node_modules/.bin/nest start --watch
    environment:
      - NODE_ENV=development
      - RMQ_HOST=rmq0
      - RMQ_PORT=5672
      - RMQ_USERNAME=guest
      - RMQ_PASSWORD=guest
      - MONGO_URI=mongodb://ritta:password@messages_db:27017/ritta-{TENANTID}?authSource=admin
    networks:
      - rabbitmq
      - services
      - databases
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - ../../logs/messages.log:/app/apps/messages/logs/all.log
      - ../../apps/messages:/app/apps/messages
      - ../../apps/messages/dist:/app/apps/messages/dist
      - ../../apps/messages/node_modules:/app/apps/messages/node_modules
