version: '3.6'

networks:
  rabbitmq-prometheus: null
  grafana:
    external:
      name: ritta-grafana
  rabbitmq:
    external:
      name: ritta-rmq

volumes:
  rabbitmq-prometheus_prometheus: null
services:
  rmq0:
    # https://hub.docker.com/r/pivotalrabbitmq/rabbitmq/tags
    &rabbitmq
    image: pivotalrabbitmq/rabbitmq:master-otp-max
    networks:
      - "rabbitmq-prometheus"
      - "rabbitmq"
      # ports: 
      # - "15673:15672" # commented out for security, remove if you want to expose the port
      # - "15693:15692" # commented out for security, remove if you want to expose the port
      # https://unix.stackexchange.com/questions/71940/killing-tcp-connection-in-linux
      # https://en.wikipedia.org/wiki/Tcpkill
      # https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands#block-an-ip-address
    cap_add:
      - ALL
    hostname: rmq0
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-prometheus
      # Uncomment the following line if you want debug logs & colour
      # RABBITMQ_LOG: debug,+color
    volumes:
      # This does not work that well on Windows
      # https://github.com/rabbitmq/rabbitmq-prometheus/commit/c4b04ea9bae877ff7d22a7085475965016933d91#commitcomment-40660523
      # - ./erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./overview.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./overview-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json:ro
  rmq-prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:v2.28.1
    networks:
      - "rabbitmq-prometheus"
      - "grafana"
    volumes:
      - rabbitmq-prometheus_prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
