name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for leaving your first issue! Feedback is very important and your issue matters to us, thank you!'
        pr-message: 'Thank you for leaving your first pull request!'
