--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
        with: 
          ref: development
      - 
        name: "Install modules"
        run: "npm install"
      - 
        name: "Run tests"
        run: "npm test"
name: "Jest tests"
true: 
  pull_request: 
    branches: 
      - development
  push: 
    branches: 
      - development
  schedule: 
    - 
      cron: "0 0 * * *"
  workflow_dispatch: 
    inputs: 
      name: 
        default: Jest
        description: "Run Jest"
        required: true
